version: '3.9'

services:
  java_app:
    container_name: java_app
    image: pee-java-app:1.0.0
    build: *
    ports:
      - 8080:8080
    environment:
      - datasource_url =jdbc:mysql://localhost:3306/bankinc
      - datasource_username=root
      - datasource_password=12345
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql
    ports:
      - 5432:5432
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DB: mysql